ipfs/helia-http-gateway

- .github/workflows/playwright.yml
- .gitignore
- README.md
- e2e-tests/compare-to-ipfs-io.spec.ts
- package-lock.json
- package.json
- playwright.config.ts
- tsconfig.json
Adds playwright tests against all the URLs that probelab.io/websites currently tests against.
URLs that are failing are currently commented out. Initial results (on helia@2.0.3) running in parallel:
> feat: add playwright tests

- .dockerignore
- .github/workflows/playwright.yml
- .gitignore
- Dockerfile
- README.md
- docker-compose.yml
- package-lock.json
- package.json
- src/constants.ts
- src/getCustomHelia.ts
- src/heliaFetch.ts
- src/heliaServer.ts
- src/index.ts
- fix: docker and naming improvements
- fix: graceful shutdown and docker cleanup
- feat: more docker ignore and smaller prod image
**For best practices, see:**
* https://snyk.io/blog/10-best-practices-to-containerize-nodejs-web-applications-with-docker/
* https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
* https://nodejs.org/en/docs/guides/nodejs-docker-webapp
---
```sh
$ docker inspect -f "{{ .Size }}" helia-docker-server | numfmt --to=si                                                                           
2.1G
```
```sh
$ docker inspect -f "{{ .Size }}" helia-docker-helia-http-gateway | numfmt --to=si
712M
```
> feat: use production level docker settings

- src/heliaServer.ts
- fix: convert CIDv0 to CIDv1 subdomains
https://github.com/ipfs/helia-http-gateway/issues/37#issuecomment-1780590462
> fix: convert CIDv0 to CIDv1 subdomains

- README.md
- src/constants.ts
- src/heliaFetch.ts
- src/heliaServer.ts
- feat: handle redirects via option default=true
> feat: handle redirects via option default=true

- src/heliaServer.ts
Each request can kick of a lot of abortable work so the abort signal created will have a lot of listeners attached to it.
This is expected, but node will print a warning message that people can mistake for an error so increase the number of listeners allowed to silence the warning.
> fix: silence max listeners exceeded warning

- package-lock.json
- package.json
- src/heliaFetch.ts
`fs.ls` tells you the type of every directory entry - to do this it loads the first block of each entry to parse the unixfs metadata - this is obviously bad news for very large directories.
Switch to `fs.stat` which only loads the directory entry we are interested in.
> fix: use fs.stat to detect directory index

- package-lock.json
- package.json
- src/index.ts
Compresses compressible content-types automatically. Significantly reduces the size of bytes we're returning to the front-end and should help with response times.
tested with
```shell
> curl http://blog.libp2p.io.ipns.localhost:8080/index.html --silent --write-out "%{size_download}\n" --output /dev/null
45840
> curl http://blog.libp2p.io.ipns.localhost:8080/index.html -H "Accept-Encoding: gzip,deflate" --silent --write-out "%{size_download}\n" --output /dev/null
5592
```
Not running against main branch because gc was removed in #60 which makes it significantly faster.
```
❯ PW_TEST_HTML_REPORT_OPEN="never" hyperfine --parameter-list branch test/e2e-smoketest-remove-gc,tmp --setup "git switch {branch} && npm i && npm run build" --runs 20  -w 1 "npm run test:e2e"
╰─ ✘ INT ❯ …
```
> feat: add @fastify/compress

- src/dns-link-labels.ts
- src/heliaServer.ts
redirects `localhost:8080/ipns/some.domain.with.dots` to `some-domain-with-dots.ipns.localhost:8080` when subdomain use is enabled
> fix: redirect to proper encoded dnslink subdomain

- README.md
- package-lock.json
- package.json
- src/getCustomLibp2p.ts
Updates the default custom libp2p config to enable missing transports, configure the DHT correctly and to collect prometheus metrics along with the default fastify ones.
Adds a note to the README about selecting the correct `prom-client` version.
> fix: update libp2p config and collect libp2p metrics

- debugging/until-death.sh
- src/helia-server.ts
- chore: make until-death script wait longer for gateway
- fix: abort signal when request stream is closed
fix: abort signal when request stream closed
Detailed description of this fix is in https://github.com/ipfs/helia-http-gateway/issues/18#issuecomment-2024211790
> fix: abort signal when request stream closed

- debugging/test-gateways.sh
- debugging/time-permutations.sh
- debugging/until-death.sh
- e2e-tests/smoketest.spec.ts
- playwright.config.ts
fix: debugging scripts and playwright config
various fixes of the debugging scripts until-death.sh and test-gateways.sh.
* shutting down the server
* shutting down subprocesses
* not logging to files (users can do this themselves when calling it if they want.)
Also added time-permutations.sh script to allow for a battery of until-death.sh scripts for debugging failures (and keeping logs around) like in #18
Also some adjustments to playwright config to allow env var overriding.
see #18 for more details
> fix: debugging scripts and playwright config

- src/constants.ts
- src/get-custom-helia.ts
- src/helia-server.ts
- src/index.ts
fix: catch uncaught exceptions & gc handles request aborts
A few changes here from https://github.com/ipfs/helia-http-gateway/issues/18#issuecomment-2027648532
1. catch uncaughtExceptions and handle if allowlisted
2. catch unhandledRejections and handle if allowlisted
3. handle empty strings in FILE_DATASTORE_PATH & FILE_BLOCKSTORE_PATH
4. pull out logic for creating a request aware signal
5. helia.gc is given a request aware signal
a lot of fixes here from discoveries made investigating https://github.com/ipfs/helia-http-gateway/issues/18
> fix: catch uncaught exceptions & gc handles request aborts

- src/get-custom-helia.ts
Helia with libp2p can use delegated http routers so pass these in to the factory function if configured.
> fix: pass routers to helia

- config/README.md
- config/docker-compose.yml
The default port of `3000` conflicts with the Chrome devtools protocol port when using tiros.
> fix: change default Graphana port

- Dockerfile
This is to better align with Kubo's behaviour and also stops the containers running out of memory really quickly since in-memory stores aren't really meant for production use.
Also turns on metrics by default and explicitly enables sub domains.
> fix: use fs stores by default in Dockerfile

- debugging/until-death.sh
Starts node with the `--inspect` flag to allow attaching a debugger.
> chore: allow attaching a debugger to debug runs

- README.md
- src/constants.ts
- src/get-custom-libp2p.ts
To use just HTTP Delegated routing:
- `USE_DHT_ROUTING=false`
- `USE_DELEGATED_ROUTING=true`
To use just DHT routing:
- `USE_DHT_ROUTING=true`
- `USE_DELEGATED_ROUTING=false`
To use both (the default):
- `USE_DHT_ROUTING=true`
- `USE_DELEGATED_ROUTING=true`
> feat: add `USE_DHT_ROUTING` env var to turn DHT on and off

- debugging/until-death.sh
Memory stores are only really meant for testing, default to using fs stores when debugging as otherwise it can look like you have a memory leak.
> fix: default to fs stores when debugging

- src/constants.ts
- src/index.ts
There are no circumstances under which it is safe to ignore uncaught exceptions, since the application is left in an unconsistent state.
The node documentation is unequivocal about this:
https://nodejs.org/api/process.html#warning-using-uncaughtexception-correctly
Any code that can throw an exception should be wrapped in a `try/catch` or there should be some other method of handling the error.
> fix: remove uncaught exception handler

- package.json
- src/helia-http-gateway.ts
We need to cancel the reader on request abort, otherwise we leak resources.
> fix: cancel stream reader on request abort

- e2e-tests/smoketest.spec.ts
Singularity's dnslink config is broken
> fix: remove singularity from smoke test

- src/healthcheck.ts
- src/helia-http-gateway.ts
- src/helia-rpc-api.ts
- src/index.ts
- src/logger.ts
Helia makes a logger available for use so use it instead of creating another one.  It prefixes log lines for us which makes component log names more intuitive.
> fix: reuse helia logger instead of creating a new one

- config/grafana/dashboards/lodestar-libp2p.json
chore: add lodestar-dashboard
Uses the libp2p dashboard used by lodestar for metrics.
Related: https://github.com/libp2p/js-libp2p/issues/2477#issuecomment-2049633373
Related: https://github.com/ChainSafe/lodestar/blob/e68a6a244e199dc6d34e9ffd6353280e8c8ee9e0/dashboards/lodestar_libp2p.json
Loaded locally and it's working well.
Only thing is since we're not listening via libp2p, three of the graphs are blank. We can remove if we want, it's an easy change.
> chore: add lodestar-dashboard

- .github/workflows/gateway-conformance.yml
- .github/workflows/playwright.yml
v3 is no longer supported as per https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: update upload-artifact action to v4
